### ISSUE TITLE
Error: failed to install 'unknown package' from github

### ISSUE THREAD

**Issue by kdbchau** [hallucigenia-sparsa/seqgroup#3]
Hi,

I tried to install your package using the following code, but I just get an odd error that I'm not sure how to fix. Please see below.

```
library(devtools)
install_github("hallucigenia-sparsa/seqgroup")
library(seqgroup)

> library(devtools)
> install_github("hallucigenia-sparsa/seqgroup")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 149.248.110.134. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2022-07-29 18:10:02 UTC

  To increase your GitHub API rate limit
  - Use `usethis::create_github_token()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
> 
```

What is going on here? Is there a package I need to install before running this code? Thank you. I should add that I had no problem installing your ```seqtime``` package using the same code as above.

**Comment by hallucigenia-sparsa** [comment]
Hi,

This is not an issue specific to seqgroup but a general problem with your github access from within R. You can try to follow the steps suggested in the error message.

Kind regards,

Karoline

**Comment by kdbchau** [comment]
I reinstalled git, restarted my computer and R and updated all packages and while it didn't work the first few times - it just now seemed to have work. Not a clue what the difference was this time - but now it magically appears to work. Thanks for the help.
